Updated the data
marsiitr/Bionic-hand-Gesture-Controller pull request #2
Opened 2023-06-19 15:22 UTC by ShivamJha1808

2023-07-18 11:41 UTC, Nageshbansal commented
@ph1ne4s review this PR asap.

2023-11-02 16:10 UTC, ph1ne4s approved these changes

2023-11-02 16:13 UTC, Shinchan9913 approved these changes

2023-11-02 16:27 UTC, Nageshbansal requested changes
Please add setup instructions

2026-05-24 13:02 UTC, merged